# Generated by Django 5.0.6 on 2024-05-24 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0003_chainevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chainevent",
            old_name="content",
            new_name="input",
        ),
    ]
