# Generated by Django 5.0.6 on 2024-06-03 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0005_chainevent_flow_chaintask_event_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chainevent",
            old_name="flow",
            new_name="flow_trace",
        ),
    ]
