# Generated by Django 5.0.6 on 2024-06-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0007_alter_chainevent_flow_trace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chaintask",
            name="event_id",
        ),
        migrations.AddField(
            model_name="chaintask",
            name="event",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="chains.chainevent",
            ),
        ),
    ]
