# Generated by Django 5.0.4 on 2024-05-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=5000)),
            ],
        ),
    ]
