# Generated by Django 5.0.6 on 2024-05-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="output",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="task",
            field=models.TextField(),
        ),
    ]
