version: '3'
services:
  redis:
    container_name: conductor-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - conductor-redis-data:/data
  postgres:
    container_name: conductor-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - conductor-postgres-data:/var/lib/postgresql/data


volume:
  conductor-redis-data:
  conductor-postgres-data: