version: '3'
services:
  redis:
    container_name: conductor-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - conductor_redis_data:/data
  postgres:
    container_name: conductor-postgres
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - conductor_postgres_data:/var/lib/postgresql/data

volumes:
  conductor_redis_data:
  conductor_postgres_data:
