version: '3'

services:
  server:
    container_name: conductor-server
    image: conductor-server-base:latest
    command: ["sh", "./start.dev.sh"]
    env_file:
      - local.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8000/swagger"]
      interval: 30s
      timeout: 10s
      retries: 5
  server-celery:
    container_name: conductor-server-celery
    image: conductor-server-base:latest
    command: ["sh", "./start.celery.sh"]
    env_file:
      - local.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  redis:
    container_name: conductor-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - conductor_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  postgres:
    container_name: conductor-postgres
    env_file:
      - local.env
    user: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - conductor_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  conductor-discord-bot:
    container_name: conductor-discord-bot
    depends_on:
      server:
        condition: service_healthy
    image: conductor-discord-bot:latest
    env_file:
      - local.env
    command: ["python", "/app/run_discord_bot.py"]
  conductor-flows-agent:
    container_name: conductor-flows-agent
    depends_on:
      server:
        condition: service_healthy
    image: conductor-flows:latest
    environment:
      - PREFECT_API_URL=http://conductor-flows-server:4200/api
      - PREFECT_UI_URL=http://conductor-flows-server:4200/api
    restart: unless-stopped
  conductor-flows-server:
    container_name: conductor-flows-server
    depends_on:
      server:
        condition: service_healthy
    image: conductor-flows:latest
    ports:
      - 4200:4200
    restart: always
    entrypoint: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_URL=http://localhost:4200/api
      - PREFECT_API_URL=http://localhost:4200/api


volumes:
  conductor_redis_data:
  conductor_postgres_data:
