version: '3'
services:
  redis:
    container_name: conductor-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - conductor_redis_data_local:/data
  postgres:
    container_name: conductor-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - conductor_postgres_data_local:/var/lib/postgresql/data

volumes:
  conductor_redis_data_local:
  conductor_postgres_data_local:
