# Generated by Django 5.0.6 on 2024-05-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowresult",
            name="context",
        ),
        migrations.AddField(
            model_name="flowresult",
            name="deployment_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="flowresult",
            name="flow_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="flowresult",
            name="prefect_id",
            field=models.UUIDField(null=True),
        ),
    ]
