# Generated by Django 5.0.6 on 2024-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0002_remove_flowresult_context_flowresult_deployment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowresult",
            name="deployment_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flowresult",
            name="flow_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flowresult",
            name="prefect_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
