# Generated by Django 5.0.6 on 2024-06-03 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0003_alter_flowresult_deployment_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowresult",
            name="deployment_id",
        ),
        migrations.RemoveField(
            model_name="flowresult",
            name="flow_id",
        ),
        migrations.RemoveField(
            model_name="flowresult",
            name="prefect_id",
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prefect_id", models.CharField(max_length=255, null=True)),
                ("prefect_flow_id", models.CharField(max_length=255, null=True)),
                ("prefect_deployment_id", models.CharField(max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flowresult",
            name="flow",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="flows.flow"
            ),
            preserve_default=False,
        ),
    ]
