# Generated by Django 5.0.6 on 2024-06-03 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0006_rename_flow_chainevent_flow_trace"),
        ("flows", "0004_remove_flowresult_deployment_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Flow",
            new_name="FlowTrace",
        ),
        migrations.RenameField(
            model_name="flowresult",
            old_name="flow",
            new_name="flow_trace",
        ),
    ]
