# Generated by Django 5.0.6 on 2024-06-04 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0006_flowtrace_prefect_name_flowtrace_prefect_parameters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowtrace",
            name="prefect_id",
        ),
    ]
