# Generated by Django 5.0.6 on 2024-06-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0007_remove_flowtrace_prefect_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowresult",
            name="flow_trace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="flows.flowtrace",
            ),
        ),
    ]
