# Generated by Django 5.0.6 on 2024-06-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="paragraphs",
            field=models.ManyToManyField(
                related_name="paragraphs", to="reports.paragraph"
            ),
        ),
    ]
