# Generated by Django 5.0.6 on 2024-06-08 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_report_paragraphs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="paragraphs",
        ),
        migrations.AddField(
            model_name="paragraph",
            name="report",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paragraphs",
                to="reports.report",
            ),
        ),
    ]
