# Generated by Django 5.0.6 on 2024-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_remove_paragraph_report_report_paragraphs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="paragraphs",
            field=models.ManyToManyField(to="reports.paragraph"),
        ),
    ]
