# Generated by Django 5.0.6 on 2024-06-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_alter_report_paragraphs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="paragraphs",
            field=models.ManyToManyField(
                related_name="paragraphs", to="reports.paragraph"
            ),
        ),
    ]
