# Generated by Django 5.0.6 on 2024-06-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0007_alter_chainevent_flow_trace"),
        ("reports", "0006_alter_report_paragraphs"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="chains.chaintask",
            ),
        ),
    ]
