# Generated by Django 5.0.6 on 2024-06-15 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_report_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="paragraphs",
        ),
        migrations.AddField(
            model_name="report",
            name="sections",
            field=models.ManyToManyField(
                related_name="sections", to="reports.paragraph"
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paragraphs",
                    models.ManyToManyField(
                        related_name="paragraphs", to="reports.paragraph"
                    ),
                ),
            ],
        ),
    ]
