# Generated by Django 5.0.6 on 2024-06-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_remove_report_paragraphs_report_sections_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="sections",
            field=models.ManyToManyField(related_name="sections", to="reports.section"),
        ),
    ]
