# Generated by Django 5.0.6 on 2024-06-21 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0007_alter_chainevent_flow_trace"),
        ("reports", "0010_report_raw"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="description",
        ),
        migrations.RemoveField(
            model_name="report",
            name="sections",
        ),
        migrations.RemoveField(
            model_name="report",
            name="task",
        ),
        migrations.RemoveField(
            model_name="report",
            name="title",
        ),
        migrations.AddField(
            model_name="report",
            name="style",
            field=models.CharField(
                choices=[
                    ("BULLETED", "as bulleted lists, avoiding long paragraphs."),
                    (
                        "NARRATIVE",
                        "as long form narratives, avoiding bullet points and short sentences.",
                    ),
                ],
                default="BULLETED",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="raw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ParsedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        related_name="sections", to="reports.section"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="chains.chaintask",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.parsedreport",
            ),
        ),
    ]
