# Generated by Django 5.0.6 on 2024-06-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0011_remove_report_description_remove_report_sections_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="reports.parsedreport",
            ),
        ),
    ]
