# Generated by Django 5.0.6 on 2024-06-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
        ("reports", "0012_alter_report_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="crew_run",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew_run",
                to="agents.crewrun",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="style",
            field=models.CharField(
                choices=[
                    ("BULLETED", "as bulleted lists, avoiding long paragraphs."),
                    (
                        "NARRATIVE",
                        "as long form narratives, avoiding bullet points and short sentences.",
                    ),
                ],
                default="as bulleted lists, avoiding long paragraphs.",
                max_length=255,
            ),
        ),
    ]
