# Generated by Django 5.0.6 on 2024-06-22 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0007_alter_chainevent_flow_trace"),
        ("reports", "0013_report_crew_run_alter_report_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsedreport",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to="chains.chaintask",
            ),
        ),
    ]
